import { MigrationInterface, QueryRunner } from "typeorm";

export class AddCoreEntities1779103926642 implements MigrationInterface {
    name = 'AddCoreEntities1779103926642'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" character varying NOT NULL, "client_id" character varying NOT NULL, "sale_id" character varying NOT NULL, "plan_id" character varying NOT NULL, "plan_version_id" character varying NOT NULL, "plan_name" character varying NOT NULL, "recurring_value" numeric(10,2) NOT NULL, "dependent_rule" character varying(20) NOT NULL, "dependent_count" integer NOT NULL DEFAULT '0', "status" character varying(30) NOT NULL DEFAULT 'ativa', "start_date" date NOT NULL, "cancel_reason" character varying(500), "cancelled_by_id" character varying, "cancelled_at" TIMESTAMP WITH TIME ZONE, "asaas_subscription_id" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_94158192bcd77997010d7763b4" ON "subscriptions" ("tenant_id", "client_id") `);
        await queryRunner.query(`CREATE TABLE "sales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" character varying NOT NULL, "opportunity_id" character varying NOT NULL, "seller_id" character varying NOT NULL, "team_id" character varying, "plan_id" character varying NOT NULL, "plan_version_id" character varying NOT NULL, "plan_snapshot" jsonb NOT NULL, "dependent_count" integer NOT NULL DEFAULT '0', "total_lives" integer NOT NULL DEFAULT '1', "base_value" numeric(10,2) NOT NULL, "dependents_value" numeric(10,2) NOT NULL DEFAULT '0', "admission_fee" numeric(10,2), "subtotal" numeric(10,2) NOT NULL, "discount" numeric(10,2) NOT NULL DEFAULT '0', "total_value" numeric(10,2) NOT NULL, "calculation_memory" jsonb NOT NULL, "payment_method" character varying(20) NOT NULL, "status" character varying(30) NOT NULL DEFAULT 'pending_payment', "asaas_customer_id" character varying(50), "asaas_payment_id" character varying(50), "asaas_checkout_url" character varying(500), "asaas_bankslip_url" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4f0bc990ae81dba46da680895ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "opportunities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" character varying NOT NULL, "seller_id" character varying NOT NULL, "name" character varying NOT NULL, "document" character varying(18) NOT NULL, "document_normalized" character varying(14) NOT NULL, "phone" character varying(20), "email" character varying(255), "birth_date" date, "postal_code" character varying(9), "address" character varying(255), "address_number" character varying(20), "address_complement" character varying(100), "neighborhood" character varying(100), "city" character varying(100), "state" character varying(2), "plan_version_id" character varying, "payment_method" character varying(20), "status" character varying(20) NOT NULL DEFAULT 'aberta', "cancel_reason" character varying(500), "cancelled_by_id" character varying, "cancelled_at" TIMESTAMP WITH TIME ZONE, "asaas_customer_id" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4bd9cd12ddc0ff48a5a97ddebce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_18e44a3407c571924b2df65f05" ON "opportunities" ("tenant_id", "document_normalized") `);
        await queryRunner.query(`CREATE TABLE "opportunity_dependents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "opportunity_id" character varying NOT NULL, "name" character varying NOT NULL, "document" character varying(18) NOT NULL, "document_normalized" character varying(14) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_658b070a26ab73df589964cd3ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "clients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" character varying NOT NULL, "opportunity_id" character varying NOT NULL, "seller_id" character varying NOT NULL, "type" character varying(10) NOT NULL, "holder_id" character varying, "name" character varying NOT NULL, "document" character varying(18) NOT NULL, "document_normalized" character varying(14) NOT NULL, "phone" character varying(20), "email" character varying(255), "birth_date" date, "postal_code" character varying(9), "address" character varying(255), "address_number" character varying(20), "address_complement" character varying(100), "neighborhood" character varying(100), "city" character varying(100), "state" character varying(2), "status" character varying(30) NOT NULL DEFAULT 'ativo', "asaas_customer_id" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f1ab7cf3a5714dbc6bb4e1c28a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ed00c8b73123d3068a7fa75f46" ON "clients" ("tenant_id", "document_normalized") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_ed00c8b73123d3068a7fa75f46"`);
        await queryRunner.query(`DROP TABLE "clients"`);
        await queryRunner.query(`DROP TABLE "opportunity_dependents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18e44a3407c571924b2df65f05"`);
        await queryRunner.query(`DROP TABLE "opportunities"`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94158192bcd77997010d7763b4"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
    }

}
